/* 
 * File:   COMPILER.H
 * Author: omars
 *
 * Created on June 24, 2024, 10:27 AM
 */

#ifndef COMPILER_H
#define	COMPILER_H

/* ********************** Includes Section Start ********************** */

/* ********************** Includes Section End   ********************** */

/* ********************** Macro Section Start ************************* */

/* ********************** Macro Section End   ************************* */

/* ********************** Macro functions Section Start ************************* */

/* ********************** Macro functions Section End   ************************* */

/* ********************** Data type Section Start ************************* */

/* ********************** Data type functions Section End   ************************* */

/* **********************  functions declarations Section Start ************************* */

/* **********************  functions declarations Section End   ************************* */



#endif	/* COMPILER_H */

